# Population settings
population:
  num_customers: 10000
  num_merchants: 500
  cards_per_customer:
    min: 1
    max: 4

# Transaction settings
transactions:
  total_transactions: 100000
  amount_range:
    min: 50.00
    max: 100.00
  date_range:
    start: '2023-01-01'
    end: '2024-01-01'
  # Legitimate chargeback settings
  legitimate_chargebacks:
    rate: 0.02  # 2% legitimate chargeback rate
    reasons:
      product_not_received: 0.30
      product_defective: 0.25
      duplicate_charge: 0.15
      incorrect_amount: 0.20
      service_not_provided: 0.10
    chargeback_delay:
      min: 1
      max: 60

# Serial Chargeback Pattern Injection settings
pattern_injection:
  customer_ratio: 0.001
  chargebacks_in_pattern:
    min: 5
    max: 8
  time_window:
    min: 7   # days
    max: 30  # days
  repeat_merchant_prob: 0.4  # 40% chance to use same merchant
  chargeback_delay:
    min: 3   # days
    max: 14  # days
  reasons:
    product_not_received: 0.60
    service_not_provided: 0.25
    product_defective: 0.15 