# Population settings
population:
  num_customers: 10000
  num_merchants: 500
  cards_per_customer:
    min: 1
    max: 3

# Transaction settings
transactions:
  num_transactions: 100000
  amount:
    min: 10.00
    max: 500.00
  date_range:
    start: '2025-01-01'
    end: '2025-12-31'
  legitimate_chargebacks:
    rate: 0.02
    delay:
      min: 15
      max: 45

# Fraud Pattern Settings
fraud_patterns:
  total_fraud_ratio: 0.1
  pattern_distribution:
    serial_chargeback: 0.1
    bin_attack: 0.1
    friendly_fraud: 0.1
    geographic_mismatch: 0.7

  # Serial Chargeback Pattern settings
  serial_chargeback:
    # Number of transactions in each pattern
    transactions_in_pattern:
      min: 5
      max: 7
    # Time window for pattern (in days)
    time_window:
      min: 10
      max: 15
    # Probability of reusing a merchant
    merchant_reuse_prob: 0.8
    # Probability of a transaction becoming a chargeback
    chargeback_probability: 0.8
    # Delay between transaction and chargeback (in days)
    chargeback_delay:
      min: 10
      max: 30

  # Friendly Fraud Pattern settings
  friendly_fraud:
    # Initial legitimate period (in days)
    legitimate_period:
      min: 30
      max: 40
    # Number of transactions before starting chargebacks
    initial_legitimate_transactions:
      min: 3
      max: 5
    # Number of fraudulent transactions after legitimate period
    fraudulent_transactions:
      min: 4
      max: 8
    # Time between transactions (in days)
    time_between_transactions:
      min: 10
      max: 20
    # Transaction amounts should be within normal range
    transaction_amount:
      min: 40.00
      max: 75.00
    # Delay between transaction and chargeback (in days)
    chargeback_delay:
      min: 50
      max: 80
    # Probability of a transaction becoming a chargeback after legitimate period
    chargeback_probability: 0.7
    # Merchant reuse probability (should be low to spread across merchants)
    merchant_reuse_prob: 0.1

  # BIN Attack Pattern settings
  bin_attack:
    # BIN prefixes to use (first 6 digits of card numbers)
    bin_prefixes: 
      - "123456"
      - "789012"
      - "123222"
      - "129994"
    # Number of cards to use in attack
    num_cards:
      min: 15
      max: 25
    # Time window for pattern (in minutes)
    time_window:
      minutes: 60
    # Small transaction amounts for testing
    transaction_amount:
      min: 1.00
      max: 5.00
    # Probability of reusing a merchant
    merchant_reuse_prob: 0.7
    # Probability of a transaction becoming a chargeback
    chargeback_probability: 0.8
    # Delay between transaction and chargeback (in days)
    chargeback_delay:
      min: 30
      max: 60

  # Geographic Mismatch Pattern settings
  geographic_mismatch:
    # Number of transactions per pattern
    num_transactions:
      min: 2
      max: 5
    # Time window for pattern (in days)
    time_window:
      min: 1
      max: 7
    # Transaction amounts (moderate amounts for plausible purchases)
    transaction_amount:
      min: 50.00
      max: 200.00
    # Probability of reusing a merchant
    merchant_reuse_prob: 0.3
    # Probability of a transaction becoming a chargeback
    chargeback_probability: 0.9
    # Delay between transaction and chargeback (in days)
    chargeback_delay:
      min: 20
      max: 45