# Population settings
population:
  num_customers: 10000
  num_merchants: 500
  cards_per_customer:
    min: 1
    max: 3

# Transaction settings
transactions:
  num_transactions: 100000
  amount:
    min: 10.00
    max: 500.00
  date_range:
    start: '2025-01-01'
    end: '2025-12-31'
  legitimate_chargebacks:
    rate: 0.02
    delay:
      min: 15
      max: 45

# Fraud Pattern Settings
fraud_patterns:
  total_fraud_ratio: 0.15
  pattern_distribution:
    serial_chargeback: 0.6
    bin_attack: 0.4

  # Serial Chargeback Pattern settings
  serial_chargeback:
    # Number of transactions in each pattern
    transactions_in_pattern:
      min: 5
      max: 7
    # Time window for pattern (in days)
    time_window:
      min: 10
      max: 15
    # Probability of reusing a merchant
    merchant_reuse_prob: 0.8
    # Delay between transaction and chargeback (in days)
    chargeback_delay:
      min: 10
      max: 30

  # BIN Attack Pattern settings
  bin_attack:
    # BIN prefixes to use (first 6 digits of card numbers)
    bin_prefixes: 
      - "123456"
      - "789012"
      - "123222"
      - "129994"
    # Number of cards to use in attack
    num_cards:
      min: 15
      max: 25
    # Number of merchants to target
    num_merchants:
      min: 3
      max: 7
    # Time window for pattern (in minutes)
    time_window:
      minutes: 60
    # Small transaction amounts for testing
    transaction_amount:
      min: 1.00
      max: 5.00
    # Probability of reusing a merchant
    merchant_reuse_prob: 0.7
    # Percentage of transactions that result in chargebacks
    chargeback_rate: 0.8
    # Delay between transaction and chargeback (in days)
    chargeback_delay:
      min: 30
      max: 60